### ISSUE TITLE
Does skit have a todomvc?

### ISSUE THREAD

**Issue by farzher** [clusterinc/skit#6]
todomvc.com is one of my favorite ways to compare frameworks.

I think a nice todomvc example would help convince people that your framework is worth trying

**Comment by flyingmutant** [comment]
:+1:

**Comment by taylorhughes** [comment]
Good idea!

**Comment by psaitu** [comment]
+1

**Comment by bmull** [comment]
+1

**Comment by taylorhughes** [comment]
This is here: http://todomvc.skitjs.com/ (work in progress -- editing not done yet)

Source: https://github.com/taylorhughes/skit-todomvc

I can't actually include it in TodoMVC proper AFAIK because it requires a separate server-side process, not just a statically served set of resources like normal client-side frameworks.
